config/routes.rb
Rails.application.routes.draw do
  resources :event_attendances, only: %i[create destroy]
  resources :event_invitations, only: %i[new create destroy]
  resources :events
  devise_for :users
  resources :users, only: [:show]
  root to: 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: 'creator_id', class_name: 'User'
  has_many :event_attendances
  has_many :attendees, through: :event_attendances, source: :attendee

  has_many :event_invitations
  has_many :invited, through: :event_invitations, source: :user

  validates :name, :desc, :date, presence: true

  scope :upcoming, -> { where('date > ?', DateTime.now) }
  scope :past, -> { where('date < ?', DateTime.now) }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :event

  validates :attendee, uniqueness: { scope: :event }
end

app/models/event_invitation.rb
class EventInvitation < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user, uniqueness: { scope: :event, message: 'already invited.' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:username]

  validates :username, presence: true, uniqueness: true

  has_many :event_attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendances, source: :event

  has_many :events, foreign_key: :creator_id

  has_many :event_invitations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[username email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: %i[username password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  before_action :set_event_attendance, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # POST /event_attendances or /event_attendances.json
  def create
    @event_attendance = current_user.event_attendances.new(event_attendance_params)

    respond_to do |format|
      if @event_attendance.save
        format.html { redirect_back fallback_location: root_path }
        format.json { render :show, status: :created, location: @event_attendance }
      else
        format.html { redirect_back fallback_location: root_path }
        format.json { render json: @event_attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_attendances/1 or /event_attendances/1.json
  def destroy
    @event_attendance.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event_attendance
    @event_attendance = EventAttendance.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_attendance_params
    params.require(:event_attendance).permit(:event_id)
  end
end

app/controllers/event_invitations_controller.rb
class EventInvitationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @invitation = EventInvitation.new(invitation_params)
  end

  def create
    @invitation = EventInvitation.new(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to @invitation.event, notice: 'Invitation was successfully created.' }
      else
        format.html { redirect_back fallback_location: root_path, notice: @invitation.errors.full_messages.to_sentence }
      end
    end
  end

  private

  def invitation_params
    params.require(:event_invitation).permit(:user_id, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /events or /events.json
  def index
    @events = Event.order(:date).includes(:creator, :attendees).all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :desc, :date, :invite_only)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/event_invitations_helper.rb
module EventInvitationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendances/_form.html.erb
<%= form_with(model: event_attendance) do |form| %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_attendances/edit.html.erb
<h1>Editing Event Attendance</h1>

<%= render 'form', event_attendance: @event_attendance %>

<%= link_to 'Show', @event_attendance %> |
<%= link_to 'Back', event_attendances_path %>

app/views/event_attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Attendances</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_attendances.each do |event_attendance| %>
      <tr>
        <td><%= link_to 'Show', event_attendance %></td>
        <td><%= link_to 'Edit', edit_event_attendance_path(event_attendance) %></td>
        <td><%= link_to 'Destroy', event_attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Attendance', new_event_attendance_path %>

app/views/event_attendances/new.html.erb
<h1>New Event Attendance</h1>

<%= render 'form', event_attendance: @event_attendance %>

<%= link_to 'Back', event_attendances_path %>

app/views/event_attendances/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_attendance_path(@event_attendance) %> |
<%= link_to 'Back', event_attendances_path %>

app/views/event_invitations/new.html.erb
<section class="column small-gap">
  <h2>Create Invitation</h2>
  <%= form_with(model: @invitation, url: event_invitations_path, class: 'column small-gap') do |form| %>
    <section>
      <%= form.label :user_id %>
      <%= form.collection_select :user_id, User.where.not(id: current_user).all, :id, :username %>
    </section>

    <section>
      <%= form.hidden_field :event_id %>
      <%= form.submit :create %>
    </section>
  <% end %>
  <section class="links">
    <%= link_to 'back', @invitation.event %>
  </section>
</section>

app/views/events/_form.html.erb
<%= form_with(model: event, class: 'column small-gap') do |form| %>
  <% if event.errors.any? %>
    <section id="error_explanation">
      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </section>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :invite_only %>
    <%= form.check_box :invite_only %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<section class="edit-event">
  <h2>Editing Event</h2>

  <%= render 'form', event: @event %>

  <section class="links">
    <%= link_to 'Show', @event %>
    <%= link_to 'Back', events_path %>
  </section>
<section>

app/views/events/index.html.erb
<section class="row normal-gap">
  <section class="column normal-gap">
    <h2>Upcoming Events</h2>
    <% @events.upcoming.each do |event| %>
      <article class="card">
        <h2><%= link_to event.name, event_path(event) %></h2>
        <p><strong>Creator</strong>: <%= link_to event.creator.username, user_path(event.creator) %></p>
        <p><strong>Description</strong>: <%= event.desc %></p>
        <p><strong>Date</strong>: <%= event.date %></p>
        <p><strong>Attending</strong>: <%= event.attendees.size %></p>
      </article>
    <% end %>
  </section>
  <section class="column normal-gap">
    <h2>Past Events</h2>
    <% @events.past.reorder(date: :desc).each do |event| %>
      <article class="card">
        <h2><%= link_to event.name, event_path(event) %></h2>
        <p><strong>Creator</strong>: <%= link_to event.creator.username, user_path(event.creator) %></p>
        <p><strong>Description</strong>: <%= event.desc %></p>
        <p><strong>Date</strong>: <%= event.date %></p>
        <p><strong>Attending</strong>: <%= event.attendees.size %></p>
      </article>
    <% end %>
  </section>
</section>

app/views/events/new.html.erb
<section class="column small-gap">
  <h2>New Event</h2>

  <%= render 'form', event: @event %>

  <%= link_to 'Back', events_path %>
</section>

app/views/events/show.html.erb
<section>
  <p>
    <strong>Name:</strong>
    <%= @event.name %>
  </p>

  <p>
    <strong>Desc:</strong>
    <%= @event.desc %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @event.date %>
  </p>

  <p>
    <strong>Creator:</strong>
    <%= link_to @event.creator.username, user_path(@event.creator) %>
  </p>

  <p>
    <strong>Invite Only:</strong>
    <%= @event.invite_only ? 'yes' : 'no' %>
  </p>

  <p>
    <strong>Invited:</strong>
    <% if @event.invited.size == 0 %>
      None
    <% else %>
      <% @event.invited.each do |user| %>
        <%= link_to user.username, user_path(user) %>
      <% end %>
    <% end %>
  </p>

  <p>
    <strong>Attendees:</strong>
    <% if @event.attendees.size == 0 %>
      None
    <% else %>
      <% @event.attendees.each do |user| %>
        <%= link_to user.username, user_path(user) %>
      <% end %>
    <% end %>
  </p>

  <hr>

  <section class="links">
    <% if user_signed_in? %>
      <% if current_user == @event.creator %>
        <%= link_to 'Edit', edit_event_path(@event) %>
        <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Invite', new_event_invitation_path(event_invitation: { event_id: @event }) %>
      <% elsif @event.invited.exists?(current_user.id) %>
        <% if current_user.attended_events.exists?(@event.id) %>
          <%= link_to 'Dont Attend', event_attendance_path(id: current_user.event_attendances.find_by(event_id: @event.id).id), method: :delete %>
        <% else %>
          <%= link_to 'Attend', event_attendances_path(event_attendance: {event_id: @event.id}), method: :post %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to 'Log In to attend event', new_user_session_path %>
    <% end %>
    <%= link_to 'Back', :back %>
  </section>
<section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="main-header">
      <h1><%= link_to 'Private Events', root_path %></h1>
      <nav>
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to 'Create Event', new_event_path %></li>
            <li><%= link_to current_user.username, user_path(current_user) %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <section class="column small-gap">
      <% flash.each do |type, message| %>
        <p><%= "#{message}" %></p>
      <% end %>
    </section>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/show.html.erb
<section class="column normal-gap">
  <h2><%= @user.username %></h2>
  <section class="row normal-gap">
    <section class="card column small-gap">
      <h3>Created Events:</h3>
      <% @user.events.each do |event| %>
        <section>
          <p><%= link_to event.name, event_path(event) %></p>
        </section>
      <% end %>
    </section>
    <section class="card column small-gap">
      <h3>Attended Events:</h3>
      <h4>Upcoming Events:</h4>
      <% @user.attended_events.upcoming.each do |event| %>
        <section>
          <p><%= link_to event.name, event_path(event) %></p>
        </section>
      <% end %>
      <h4>Past Events:</h4>
      <% @user.attended_events.past.each do |event| %>
        <section>
          <p><%= link_to event.name, event_path(event) %></p>
        </section>
      <% end %>
    </section>
  </section>
</section>